// autogenerated by DarkClan.Encicl.ACToJS 1.199.29.0
var expd = {
	L0: {id: 0, count: 4, body: 'Физическое', baseExp: 5, ups: {
		U0: {id: 0, sexp: 0, aendurance: 0, amastery: 0, sstats: 15, astats: 3, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 25, aendurance: 0, amastery: 0, sstats: 16, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 45, aendurance: 0, amastery: 0, sstats: 17, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 75, aendurance: 0, amastery: 0, sstats: 18, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L1: {id: 1, count: 5, body: 'Физическое', baseExp: 10, description: 'Физические бои, доступ в форум', ups: {
		U0: {id: 0, sexp: 110, aendurance: 1, amastery: 2, sstats: 22, astats: 3, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 160, aendurance: 0, amastery: 0, sstats: 23, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 215, aendurance: 0, amastery: 0, sstats: 24, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 280, aendurance: 0, amastery: 0, sstats: 25, astats: 1, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 350, aendurance: 0, amastery: 0, sstats: 26, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L2: {id: 2, count: 6, body: 'Физическое', baseExp: 20, description: 'Групповые и Хаотические бои', ups: {
		U0: {id: 0, sexp: 410, aendurance: 1, amastery: 1, sstats: 30, astats: 3, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 530, aendurance: 0, amastery: 0, sstats: 31, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 670, aendurance: 0, amastery: 0, sstats: 32, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 830, aendurance: 0, amastery: 0, sstats: 33, astats: 1, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 950, aendurance: 0, amastery: 0, sstats: 34, astats: 1, scredits: 0, acredits: 0
		},
		U5: {id: 5, sexp: 1100, aendurance: 0, amastery: 0, sstats: 35, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L3: {id: 3, count: 6, body: 'Физическое', baseExp: 30, description: 'Настройка комплектов одежды', ups: {
		U0: {id: 0, sexp: 1300, aendurance: 1, amastery: 1, sstats: 39, astats: 3, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 1450, aendurance: 0, amastery: 0, sstats: 40, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 1650, aendurance: 0, amastery: 0, sstats: 41, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 1850, aendurance: 0, amastery: 0, sstats: 42, astats: 1, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 2050, aendurance: 0, amastery: 0, sstats: 43, astats: 1, scredits: 0, acredits: 0
		},
		U5: {id: 5, sexp: 2200, aendurance: 0, amastery: 0, sstats: 44, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L4: {id: 4, count: 6, body: 'Эмоций', baseExp: 60, description: 'Развитие интеллекта (чтение свитков), доступ в Рыцарский Зал и Торговый Зал, передача предметов / кредитов', ups: {
		U0: {id: 0, sexp: 2500, aendurance: 1, amastery: 1, sstats: 50, astats: 5, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 2900, aendurance: 0, amastery: 0, sstats: 51, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 3350, aendurance: 0, amastery: 0, sstats: 52, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 3800, aendurance: 0, amastery: 0, sstats: 53, astats: 1, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 4200, aendurance: 0, amastery: 0, sstats: 54, astats: 1, scredits: 0, acredits: 0
		},
		U5: {id: 5, sexp: 4600, aendurance: 0, amastery: 0, sstats: 55, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L5: {id: 5, count: 8, body: 'Эмоций', baseExp: 120, ups: {
		U0: {id: 0, sexp: 5000, aendurance: 1, amastery: 1, sstats: 59, astats: 3, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 6000, aendurance: 0, amastery: 0, sstats: 60, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 7000, aendurance: 0, amastery: 0, sstats: 61, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 8000, aendurance: 0, amastery: 0, sstats: 62, astats: 1, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 9000, aendurance: 0, amastery: 0, sstats: 63, astats: 1, scredits: 0, acredits: 0
		},
		U5: {id: 5, sexp: 10000, aendurance: 0, amastery: 0, sstats: 64, astats: 1, scredits: 0, acredits: 0
		},
		U6: {id: 6, sexp: 11000, aendurance: 0, amastery: 0, sstats: 65, astats: 1, scredits: 0, acredits: 0
		},
		U7: {id: 7, sexp: 12000, aendurance: 0, amastery: 0, sstats: 66, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L6: {id: 6,  baseExp: 180, description: 'Доступ в Башню Смерти. Для взятия уровня необходимо купить Кристалл Знаний [6] в Каморке Луки.', ups: {
		U0: {id: 0, sexp: 12500, aendurance: 1, amastery: 1, sstats: 70, astats: 3, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 14000, aendurance: 0, amastery: 0, sstats: 71, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 15500, aendurance: 0, amastery: 0, sstats: 72, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 17000, aendurance: 0, amastery: 0, sstats: 73, astats: 1, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 19000, aendurance: 0, amastery: 0, sstats: 74, astats: 1, scredits: 0, acredits: 0
		},
		U5: {id: 5, sexp: 21000, aendurance: 0, amastery: 0, sstats: 75, astats: 1, scredits: 0, acredits: 0
		},
		U6: {id: 6, sexp: 23000, aendurance: 0, amastery: 0, sstats: 76, astats: 1, scredits: 0, acredits: 0
		},
		U7: {id: 7, sexp: 27000, aendurance: 0, amastery: 0, sstats: 77, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L7: {id: 7,  baseExp: 540, description: 'Развитие мудрости (использование Магии), доступ в Башню Рыцарей - Магов', ups: {
		U0: {id: 0, sexp: 30000, aendurance: 1, amastery: 1, sstats: 83, astats: 5, scredits: 0, acredits: 0
		},
		U1: {id: 1, sexp: 35000, aendurance: 0, amastery: 0, sstats: 84, astats: 1, scredits: 0, acredits: 0
		},
		U2: {id: 2, sexp: 40000, aendurance: 0, amastery: 0, sstats: 85, astats: 1, scredits: 0, acredits: 0
		},
		U3: {id: 3, sexp: 45000, aendurance: 0, amastery: 0, sstats: 85, astats: 0, scredits: 0, acredits: 0
		},
		U4: {id: 4, sexp: 50000, aendurance: 0, amastery: 0, sstats: 85, astats: 0, scredits: 0, acredits: 0
		},
		U5: {id: 5, sexp: 55000, aendurance: 0, amastery: 0, sstats: 86, astats: 1, scredits: 0, acredits: 0
		},
		U6: {id: 6, sexp: 60000, aendurance: 0, amastery: 0, sstats: 87, astats: 1, scredits: 0, acredits: 0
		},
		U7: {id: 7, sexp: 65000, aendurance: 0, amastery: 0, sstats: 88, astats: 1, scredits: 0, acredits: 0
		},
		U8: {id: 8, sexp: 70000, aendurance: 0, amastery: 0, sstats: 89, astats: 1, scredits: 0, acredits: 0
		},
		U9: {id: 9, sexp: 75000, aendurance: 0, amastery: 0, sstats: 90, astats: 1, scredits: 0, acredits: 0
		},
		U10: {id: 10, sexp: 80000, aendurance: 0, amastery: 0, sstats: 91, astats: 1, scredits: 0, acredits: 0
		},
		U11: {id: 11, sexp: 90000, aendurance: 0, amastery: 0, sstats: 92, astats: 1, scredits: 0, acredits: 0
		}}

	},
	L8: {id: 8,  baseExp: 1800, description: 'Доступ в Подземелья', ups: {
		U0: {id: 0, sexp: 150000, aendurance: 1, amastery: 1, sstats: 98, astats: 5, scredits: 500, acredits: 500
		},
		U1: {id: 1, sexp: 200000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 600, acredits: 100
		},
		U2: {id: 2, sexp: 300000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 700, acredits: 100
		},
		U3: {id: 3, sexp: 400000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 800, acredits: 100
		},
		U4: {id: 4, sexp: 500000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 900, acredits: 100
		},
		U5: {id: 5, sexp: 700000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 1000, acredits: 100
		},
		U6: {id: 6, sexp: 900000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 1100, acredits: 100
		},
		U7: {id: 7, sexp: 1000000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 1200, acredits: 100
		},
		U8: {id: 8, sexp: 1200000, aendurance: 0, amastery: 0, sstats: 98, astats: 0, scredits: 1300, acredits: 100
		},
		U9: {id: 9, sexp: 1500000, aendurance: 0, amastery: 0, sstats: 99, astats: 1, scredits: 1800, acredits: 500
		},
		U10: {id: 10, sexp: 1750000, aendurance: 0, amastery: 0, sstats: 100, astats: 1, scredits: 2000, acredits: 200
		},
		U11: {id: 11, sexp: 2000000, aendurance: 0, amastery: 0, sstats: 101, astats: 1, scredits: 2300, acredits: 300
		},
		U12: {id: 12, sexp: 2175000, aendurance: 0, amastery: 0, sstats: 102, astats: 1, scredits: 2400, acredits: 100
		},
		U13: {id: 13, sexp: 2300000, aendurance: 0, amastery: 0, sstats: 103, astats: 1, scredits: 2500, acredits: 100
		},
		U14: {id: 14, sexp: 2400000, aendurance: 0, amastery: 0, sstats: 104, astats: 1, scredits: 2501, acredits: 1
		},
		U15: {id: 15, sexp: 2500000, aendurance: 0, amastery: 0, sstats: 105, astats: 1, scredits: 2701, acredits: 200
		},
		U16: {id: 16, sexp: 2600000, aendurance: 0, amastery: 0, sstats: 106, astats: 1, scredits: 2801, acredits: 100
		},
		U17: {id: 17, sexp: 2800000, aendurance: 0, amastery: 0, sstats: 107, astats: 1, scredits: 3001, acredits: 200
		}}

	},
	L9: {id: 9,  baseExp: 2800, ups: {
		U0: {id: 0, sexp: 3000000, aendurance: 2, amastery: 1, sstats: 116, astats: 7, scredits: 4401, acredits: 1400
		},
		U1: {id: 1, sexp: 3250000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 4901, acredits: 500
		},
		U2: {id: 2, sexp: 3500000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 5101, acredits: 200
		},
		U3: {id: 3, sexp: 3750000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 5102, acredits: 1
		},
		U4: {id: 4, sexp: 4000000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 5352, acredits: 250
		},
		U5: {id: 5, sexp: 4250000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 5752, acredits: 400
		},
		U6: {id: 6, sexp: 4500000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 5802, acredits: 50
		},
		U7: {id: 7, sexp: 4750000, aendurance: 0, amastery: 0, sstats: 116, astats: 0, scredits: 6202, acredits: 400
		},
		U8: {id: 8, sexp: 5000000, aendurance: 0, amastery: 0, sstats: 117, astats: 1, scredits: 6552, acredits: 350
		},
		U9: {id: 9, sexp: 5250000, aendurance: 0, amastery: 0, sstats: 117, astats: 0, scredits: 6552, acredits: 350
		},
		U10: {id: 10, sexp: 5500000, aendurance: 0, amastery: 0, sstats: 117, astats: 0, scredits: 6552, acredits: 350
		},
		U11: {id: 11, sexp: 5750000, aendurance: 0, amastery: 0, sstats: 117, astats: 0, scredits: 6552, acredits: 350
		},
		U12: {id: 12, sexp: 6000000, aendurance: 0, amastery: 0, sstats: 118, astats: 1, scredits: 6552, acredits: 350
		},
		U13: {id: 13, sexp: 6250000, aendurance: 0, amastery: 0, sstats: 118, astats: 0, scredits: 6552, acredits: 350
		},
		U14: {id: 14, sexp: 6500000, aendurance: 0, amastery: 0, sstats: 119, astats: 1, scredits: 6552, acredits: 350
		},
		U15: {id: 15, sexp: 6750000, aendurance: 0, amastery: 0, sstats: 119, astats: 0, scredits: 6552, acredits: 350
		},
		U16: {id: 16, sexp: 7000000, aendurance: 0, amastery: 0, sstats: 119, astats: 0, scredits: 6552, acredits: 350
		},
		U17: {id: 17, sexp: 7250000, aendurance: 0, amastery: 0, sstats: 119, astats: 0, scredits: 6552, acredits: 350
		},
		U18: {id: 18, sexp: 7500000, aendurance: 0, amastery: 0, sstats: 120, astats: 1, scredits: 6552, acredits: 350
		},
		U19: {id: 19, sexp: 8000000, aendurance: 0, amastery: 0, sstats: 120, astats: 0, scredits: 6552, acredits: 350
		},
		U20: {id: 20, sexp: 8250000, aendurance: 0, amastery: 0, sstats: 120, astats: 0, scredits: 6552, acredits: 350
		},
		U21: {id: 21, sexp: 8500000, aendurance: 0, amastery: 0, sstats: 121, astats: 1, scredits: 6552, acredits: 350
		},
		U22: {id: 22, sexp: 8750000, aendurance: 0, amastery: 0, sstats: 121, astats: 0, scredits: 6552, acredits: 350
		},
		U23: {id: 23, sexp: 9000000, aendurance: 0, amastery: 0, sstats: 122, astats: 1, scredits: 6552, acredits: 350
		},
		U24: {id: 24, sexp: 9250000, aendurance: 0, amastery: 0, sstats: 123, astats: 1, scredits: 6552, acredits: 350
		},
		U25: {id: 25, sexp: 9500000, aendurance: 0, amastery: 0, sstats: 124, astats: 1, scredits: 6552, acredits: 350
		},
		U26: {id: 26, sexp: 9750000, aendurance: 0, amastery: 0, sstats: 125, astats: 1, scredits: 7052, acredits: 500
		}}

	},
	L10: {id: 10,  baseExp: 8400, description: 'Развитие духовности, доступ в Колдовской мир', ups: {
		U0: {id: 0, sexp: 10000000, aendurance: 3, amastery: 1, sstats: 144, astats: 9, scredits: 9452, acredits: 2400
		},
		U1: {id: 1, sexp: 11000000, aendurance: 0, amastery: 0, sstats: 145, astats: 1, scredits: 9652, acredits: 200
		},
		U2: {id: 2, sexp: 12000000, aendurance: 0, amastery: 0, sstats: 146, astats: 1, scredits: 9852, acredits: 200
		},
		U3: {id: 3, sexp: 13000000, aendurance: 0, amastery: 0, sstats: 147, astats: 1, scredits: 10052, acredits: 200
		},
		U4: {id: 4, sexp: 14000000, aendurance: 0, amastery: 0, sstats: 148, astats: 1, scredits: 10252, acredits: 200
		},
		U5: {id: 5, sexp: 15000000, aendurance: 0, amastery: 0, sstats: 149, astats: 1, scredits: 10452, acredits: 200
		},
		U6: {id: 6, sexp: 16000000, aendurance: 0, amastery: 0, sstats: 150, astats: 1, scredits: 10652, acredits: 200
		},
		U7: {id: 7, sexp: 17000000, aendurance: 0, amastery: 0, sstats: 151, astats: 1, scredits: 10852, acredits: 200
		},
		U8: {id: 8, sexp: 18000000, aendurance: 0, amastery: 0, sstats: 152, astats: 1, scredits: 11052, acredits: 200
		},
		U9: {id: 9, sexp: 19000000, aendurance: 0, amastery: 0, sstats: 153, astats: 1, scredits: 11252, acredits: 200
		},
		U10: {id: 10, sexp: 20000000, aendurance: 0, amastery: 0, sstats: 154, astats: 1, scredits: 11452, acredits: 200
		},
		U11: {id: 11, sexp: 21000000, aendurance: 0, amastery: 0, sstats: 155, astats: 1, scredits: 11452, acredits: 0
		},
		U12: {id: 12, sexp: 22000000, aendurance: 0, amastery: 0, sstats: 156, astats: 1, scredits: 11452, acredits: 0
		},
		U13: {id: 13, sexp: 23000000, aendurance: 0, amastery: 0, sstats: 157, astats: 1, scredits: 11452, acredits: 0
		},
		U14: {id: 14, sexp: 24000000, aendurance: 0, amastery: 0, sstats: 158, astats: 1, scredits: 11452, acredits: 0
		},
		U15: {id: 15, sexp: 25000000, aendurance: 0, amastery: 0, sstats: 159, astats: 1, scredits: 11452, acredits: 0
		},
		U16: {id: 16, sexp: 26000000, aendurance: 0, amastery: 0, sstats: 160, astats: 1, scredits: 11452, acredits: 0
		},
		U17: {id: 17, sexp: 27000000, aendurance: 0, amastery: 0, sstats: 161, astats: 1, scredits: 11452, acredits: 0
		},
		U18: {id: 18, sexp: 28000000, aendurance: 0, amastery: 0, sstats: 162, astats: 1, scredits: 11452, acredits: 0
		},
		U19: {id: 19, sexp: 29000000, aendurance: 0, amastery: 0, sstats: 163, astats: 1, scredits: 11452, acredits: 0
		},
		U20: {id: 20, sexp: 30000000, aendurance: 0, amastery: 0, sstats: 164, astats: 1, scredits: 11452, acredits: 0
		},
		U21: {id: 21, sexp: 31000000, aendurance: 0, amastery: 0, sstats: 165, astats: 1, scredits: 11452, acredits: 0
		},
		U22: {id: 22, sexp: 32000000, aendurance: 0, amastery: 0, sstats: 166, astats: 1, scredits: 11452, acredits: 0
		},
		U23: {id: 23, sexp: 33000000, aendurance: 0, amastery: 0, sstats: 167, astats: 1, scredits: 11452, acredits: 0
		},
		U24: {id: 24, sexp: 34000000, aendurance: 0, amastery: 0, sstats: 168, astats: 1, scredits: 11452, acredits: 0
		},
		U25: {id: 25, sexp: 35000000, aendurance: 0, amastery: 0, sstats: 169, astats: 1, scredits: 11452, acredits: 0
		},
		U26: {id: 26, sexp: 36000000, aendurance: 0, amastery: 0, sstats: 170, astats: 1, scredits: 11452, acredits: 0
		},
		U27: {id: 27, sexp: 37000000, aendurance: 0, amastery: 0, sstats: 171, astats: 1, scredits: 11452, acredits: 0
		},
		U28: {id: 28, sexp: 38000000, aendurance: 0, amastery: 0, sstats: 172, astats: 1, scredits: 11452, acredits: 0
		},
		U29: {id: 29, sexp: 39000000, aendurance: 0, amastery: 0, sstats: 173, astats: 1, scredits: 11452, acredits: 0
		},
		U30: {id: 30, sexp: 40000000, aendurance: 0, amastery: 0, sstats: 174, astats: 1, scredits: 11452, acredits: 0
		},
		U31: {id: 31, sexp: 41000000, aendurance: 0, amastery: 0, sstats: 175, astats: 1, scredits: 11452, acredits: 0
		},
		U32: {id: 32, sexp: 42000000, aendurance: 0, amastery: 0, sstats: 176, astats: 1, scredits: 11452, acredits: 0
		},
		U33: {id: 33, sexp: 43000000, aendurance: 0, amastery: 0, sstats: 177, astats: 1, scredits: 11452, acredits: 0
		},
		U34: {id: 34, sexp: 44000000, aendurance: 0, amastery: 0, sstats: 178, astats: 1, scredits: 11452, acredits: 0
		},
		U35: {id: 35, sexp: 45000000, aendurance: 0, amastery: 0, sstats: 179, astats: 1, scredits: 11452, acredits: 0
		},
		U36: {id: 36, sexp: 46000000, aendurance: 0, amastery: 0, sstats: 180, astats: 1, scredits: 11452, acredits: 0
		},
		U37: {id: 37, sexp: 47000000, aendurance: 0, amastery: 0, sstats: 181, astats: 1, scredits: 11452, acredits: 0
		},
		U38: {id: 38, sexp: 48000000, aendurance: 0, amastery: 0, sstats: 182, astats: 1, scredits: 11452, acredits: 0
		},
		U39: {id: 39, sexp: 49000000, aendurance: 0, amastery: 0, sstats: 183, astats: 1, scredits: 11452, acredits: 0
		}}

	},
	L11: {id: 11, baseExp: 12000, ups: {
		U0: {id: 0, sexp: 50000000, aendurance: 5, amastery: 1, sstats: 198, astats: 10, scredits: 11452, acredits: 0
		},
		U1: {id: 1, sexp: 52000000, aendurance: 1, amastery: 0, sstats: 199, astats: 0, scredits: 11452, acredits: 0
		},
		U2: {id: 2, sexp: 54000000, aendurance: 0, amastery: 0, sstats: 200, astats: 1, scredits: 11452, acredits: 0
		},
		U3: {id: 3, sexp: 56000000, aendurance: 0, amastery: 0, sstats: 200, astats: 0, scredits: 11452, acredits: 0
		},
		U4: {id: 4, sexp: 58000000, aendurance: 1, amastery: 0, sstats: 201, astats: 0, scredits: 11452, acredits: 0
		},
		U5: {id: 5, sexp: 60000000, aendurance: 0, amastery: 0, sstats: 202, astats: 1, scredits: 11452, acredits: 0
		},
		U6: {id: 6, sexp: 62000000, aendurance: 0, amastery: 0, sstats: 202, astats: 0, scredits: 11452, acredits: 0
		},
		U7: {id: 7, sexp: 64000000, aendurance: 1, amastery: 0, sstats: 203, astats: 0, scredits: 11452, acredits: 0
		},
		U8: {id: 8, sexp: 66000000, aendurance: 0, amastery: 0, sstats: 204, astats: 1, scredits: 11452, acredits: 0
		},
		U9: {id: 9, sexp: 68000000, aendurance: 0, amastery: 0, sstats: 204, astats: 0, scredits: 11452, acredits: 0
		},
		U10: {id: 10, sexp: 70000000, aendurance: 1, amastery: 0, sstats: 205, astats: 0, scredits: 11452, acredits: 0
		},
		U11: {id: 11, sexp: 72000000, aendurance: 0, amastery: 0, sstats: 206, astats: 1, scredits: 11452, acredits: 0
		},
		U12: {id: 12, sexp: 74000000, aendurance: 0, amastery: 0, sstats: 206, astats: 0, scredits: 11452, acredits: 0
		},
		U13: {id: 13, sexp: 76000000, aendurance: 1, amastery: 0, sstats: 207, astats: 0, scredits: 11452, acredits: 0
		},
		U14: {id: 14, sexp: 78000000, aendurance: 0, amastery: 0, sstats: 208, astats: 1, scredits: 11452, acredits: 0
		},
		U15: {id: 15, sexp: 80000000, aendurance: 0, amastery: 0, sstats: 208, astats: 0, scredits: 11452, acredits: 0
		},
		U16: {id: 16, sexp: 82000000, aendurance: 1, amastery: 0, sstats: 209, astats: 0, scredits: 11452, acredits: 0
		},
		U17: {id: 17, sexp: 84000000, aendurance: 0, amastery: 0, sstats: 210, astats: 1, scredits: 11452, acredits: 0
		},
		U18: {id: 18, sexp: 86000000, aendurance: 0, amastery: 0, sstats: 210, astats: 0, scredits: 11452, acredits: 0
		},
		U19: {id: 19, sexp: 88000000, aendurance: 1, amastery: 0, sstats: 211, astats: 0, scredits: 11452, acredits: 0
		},
		U20: {id: 20, sexp: 90000000, aendurance: 0, amastery: 0, sstats: 212, astats: 1, scredits: 11452, acredits: 0
		},
		U21: {id: 21, sexp: 92000000, aendurance: 0, amastery: 0, sstats: 212, astats: 0, scredits: 11452, acredits: 0
		},
		U22: {id: 22, sexp: 94000000, aendurance: 1, amastery: 0, sstats: 213, astats: 0, scredits: 11452, acredits: 0
		},
		U23: {id: 23, sexp: 96000000, aendurance: 0, amastery: 0, sstats: 214, astats: 1, scredits: 11452, acredits: 0
		},
		U24: {id: 24, sexp: 98000000, aendurance: 0, amastery: 0, sstats: 214, astats: 0, scredits: 11452, acredits: 0
		},
		U25: {id: 25, sexp: 100000000, aendurance: 1, amastery: 0, sstats: 215, astats: 0, scredits: 11452, acredits: 0
		},
		U26: {id: 26, sexp: 102000000, aendurance: 0, amastery: 0, sstats: 216, astats: 1, scredits: 11452, acredits: 0
		},
		U27: {id: 27, sexp: 104000000, aendurance: 0, amastery: 0, sstats: 216, astats: 0, scredits: 11452, acredits: 0
		},
		U28: {id: 28, sexp: 106000000, aendurance: 1, amastery: 0, sstats: 217, astats: 0, scredits: 11452, acredits: 0
		},
		U29: {id: 29, sexp: 108000000, aendurance: 0, amastery: 0, sstats: 218, astats: 1, scredits: 11452, acredits: 0
		},
		U30: {id: 30, sexp: 110000000, aendurance: 0, amastery: 0, sstats: 218, astats: 0, scredits: 11452, acredits: 0
		},
		U31: {id: 31, sexp: 112000000, aendurance: 1, amastery: 0, sstats: 219, astats: 0, scredits: 11452, acredits: 0
		},
		U32: {id: 32, sexp: 114000000, aendurance: 0, amastery: 0, sstats: 220, astats: 1, scredits: 11452, acredits: 0
		},
		U33: {id: 33, sexp: 116000000, aendurance: 0, amastery: 0, sstats: 220, astats: 0, scredits: 11452, acredits: 0
		},
		U34: {id: 34, sexp: 118000000, aendurance: 1, amastery: 0, sstats: 221, astats: 0, scredits: 11452, acredits: 0
		},
		U35: {id: 35, sexp: 120000000, aendurance: 0, amastery: 0, sstats: 222, astats: 1, scredits: 11452, acredits: 0
		},
		U36: {id: 36, sexp: 122000000, aendurance: 0, amastery: 0, sstats: 222, astats: 0, scredits: 11452, acredits: 0
		},
		U37: {id: 37, sexp: 124000000, aendurance: 1, amastery: 0, sstats: 223, astats: 0, scredits: 11452, acredits: 0
		},
		U38: {id: 38, sexp: 126000000, aendurance: 0, amastery: 0, sstats: 224, astats: 1, scredits: 11452, acredits: 0
		},
		U39: {id: 39, sexp: 128000000, aendurance: 0, amastery: 0, sstats: 224, astats: 0, scredits: 11452, acredits: 0
		},
		U40: {id: 40, sexp: 130000000, aendurance: 1, amastery: 0, sstats: 225, astats: 0, scredits: 11452, acredits: 0
		},
		U41: {id: 41, sexp: 132000000, aendurance: 0, amastery: 0, sstats: 226, astats: 1, scredits: 11452, acredits: 0
		},
		U42: {id: 42, sexp: 134000000, aendurance: 0, amastery: 0, sstats: 226, astats: 0, scredits: 11452, acredits: 0
		},
		U43: {id: 43, sexp: 136000000, aendurance: 1, amastery: 0, sstats: 227, astats: 0, scredits: 11452, acredits: 0
		},
		U44: {id: 44, sexp: 138000000, aendurance: 0, amastery: 0, sstats: 228, astats: 1, scredits: 11452, acredits: 0
		},
		U45: {id: 45, sexp: 140000000, aendurance: 0, amastery: 0, sstats: 228, astats: 0, scredits: 11452, acredits: 0
		},
		U46: {id: 46, sexp: 142000000, aendurance: 1, amastery: 0, sstats: 229, astats: 0, scredits: 11452, acredits: 0
		},
		U47: {id: 47, sexp: 144000000, aendurance: 0, amastery: 0, sstats: 230, astats: 1, scredits: 11452, acredits: 0
		},
		U48: {id: 48, sexp: 146000000, aendurance: 0, amastery: 0, sstats: 230, astats: 0, scredits: 11452, acredits: 0
		},
		U49: {id: 49, sexp: 148000000, aendurance: 1, amastery: 0, sstats: 231, astats: 0, scredits: 11452, acredits: 0
		}}

	},
		L12: {id: 12, baseExp: 12000, ups: {
        U0: {id: 0, sexp: 150000000, aendurance: 5, amastery: 1, sstats: 241, astats: 5, scredits: 11452, acredits: 0
		},
		U1: {id: 1, sexp: 170000000, aendurance: 1, amastery: 0, sstats: 243, astats: 1, scredits: 11452, acredits: 0
		},
		U2: {id: 2, sexp: 190000000, aendurance: 1, amastery: 0, sstats: 245, astats: 1, scredits: 11452, acredits: 0
		},
		U3: {id: 3, sexp: 210000000, aendurance: 1, amastery: 0, sstats: 247, astats: 1, scredits: 11452, acredits: 0
		},
		U4: {id: 4, sexp: 230000000, aendurance: 1, amastery: 0, sstats: 249, astats: 1, scredits: 11452, acredits: 0
		},
		U5: {id: 5, sexp: 250000000, aendurance: 1, amastery: 0, sstats: 251, astats: 1, scredits: 11452, acredits: 0
		},
		U6: {id: 6, sexp: 270000000, aendurance: 1, amastery: 0, sstats: 253, astats: 1, scredits: 11452, acredits: 0
		},
		U7: {id: 7, sexp: 290000000, aendurance: 1, amastery: 0, sstats: 255, astats: 1, scredits: 11452, acredits: 0
		},
		U8: {id: 8, sexp: 310000000, aendurance: 1, amastery: 0, sstats: 257, astats: 1, scredits: 11452, acredits: 0
		},
		U9: {id: 9, sexp: 330000000, aendurance: 1, amastery: 0, sstats: 259, astats: 1, scredits: 11452, acredits: 0
		},
		U10: {id: 10, sexp: 350000000, aendurance: 1, amastery: 0, sstats: 261, astats: 1, scredits: 11452, acredits: 0
		},
		U11: {id: 11, sexp: 370000000, aendurance: 1, amastery: 0, sstats: 263, astats: 1, scredits: 11452, acredits: 0
		},
		U12: {id: 12, sexp: 390000000, aendurance: 1, amastery: 0, sstats: 265, astats: 1, scredits: 11452, acredits: 0
		},
		U13: {id: 13, sexp: 410000000, aendurance: 1, amastery: 0, sstats: 267, astats: 1, scredits: 11452, acredits: 0
		},
		U14: {id: 14, sexp: 430000000, aendurance: 1, amastery: 0, sstats: 269, astats: 1, scredits: 11452, acredits: 0
		},
		U15: {id: 15, sexp: 450000000, aendurance: 1, amastery: 0, sstats: 271, astats: 1, scredits: 11452, acredits: 0
		},
		U16: {id: 16, sexp: 470000000, aendurance: 1, amastery: 0, sstats: 273, astats: 1, scredits: 11452, acredits: 0
		},
		U17: {id: 17, sexp: 490000000, aendurance: 1, amastery: 0, sstats: 275, astats: 1, scredits: 11452, acredits: 0
		},
		U18: {id: 18, sexp: 500000000, aendurance: 1, amastery: 1, sstats: 277, astats: 1, scredits: 11452, acredits: 0
		},
		U19: {id: 19, sexp: 650000000, aendurance: 1, amastery: 0, sstats: 279, astats: 1, scredits: 11452, acredits: 0
		},
		U20: {id: 20, sexp: 800000000, aendurance: 1, amastery: 0, sstats: 281, astats: 1, scredits: 11452, acredits: 0
		},
		U21: {id: 21, sexp: 950000000, aendurance: 1, amastery: 0, sstats: 283, astats: 1, scredits: 11452, acredits: 0
		},
		U22: {id: 22, sexp: 1150000000, aendurance: 1, amastery: 0, sstats: 285, astats: 1, scredits: 11452, acredits: 0
		},
		U23: {id: 23, sexp: 1300000000, aendurance: 1, amastery: 0, sstats: 287, astats: 1, scredits: 11452, acredits: 0
		},
		U24: {id: 24, sexp: 1450000000, aendurance: 1, amastery: 0, sstats: 289, astats: 1, scredits: 11452, acredits: 0
		
		}}

	},
	L13: {id: 13, baseExp: 6000, ups: {
	    U0: {id: 0, sexp: 1500000000, aendurance: 1, amastery: 0, sstats: 315, astats: 25, scredits: 11452, acredits: 0
		},
		U1: {id: 1, sexp: 2500000000, aendurance: 1, amastery: 0, sstats: 321, astats: 5, scredits: 11452, acredits: 0
	    },
		U2: {id: 2, sexp: 3500000000, aendurance: 1, amastery: 0, sstats: 327, astats: 5, scredits: 11452, acredits: 0
         }}

	},
	L14: {id: 14, baseExp: 7500, ups: {
     U0: {id: 0, sexp: 5500000000, aendurance: 5, amastery: 1, sstats: 367, astats: 35, scredits: 11452, acredits: 0
         }}
	},
	L15: {id: 15, baseExp: 9000, ups: {
}

	},
	L16: {id: 16, baseExp: 12000, ups: {
}

	},
	L17: {id: 17, baseExp: 15000, ups: {
}

	},
	L18: {id: 18, baseExp: 18000, ups: {
}

	},
	L19: {id: 19, baseExp: 24000, ups: {
}

	},
	L20: {id: 20, baseExp: 36000, ups: {
}

	},
	L21: {id: 21, baseExp: 50000, ups: {
}

	}};
